//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FitBooking.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

public partial class Adres
{
    public int Id { get; set; }
    [Required(ErrorMessage = "Proszę wprowadzić ulicę")]
    [RegularExpression(@"^[0-9A-ZĄĘŁŃÓŚŹŻ]+[0-9a-zA-ZąćęłńóśźżĄĘŁŃÓŚŹŻ.''-'\s]*$", ErrorMessage = "Błąd, wyrażenie powinno składać się tylko z liter")]
    public string ulica { get; set; }
    [DisplayName("numer domu")]
    [Required(ErrorMessage = "Proszę wprowadzić numer domu")]
    [RegularExpression(@"^[0-9A-Z]*$", ErrorMessage = "Błąd, wprowadzonych danych")]
    public string nr_domu { get; set; }
    [DisplayName("kod pocztowy")]
    [Required(ErrorMessage = "Proszę wprowadzić kod pocztowy")]
    [RegularExpression(@"^\d{2}-\d{3}$", ErrorMessage = "Błąd, wprowadzonych danych")]
    public string kod_pocztowy { get; set; }
    [Required(ErrorMessage = "Proszę wprowadzić miasto")]
    [RegularExpression(@"^[0-9A-ZĄĘŁŃÓŚŹŻ]+[0-9a-zA-ZąćęłńóśźżĄĘŁŃÓŚŹŻ''-'\s]*$", ErrorMessage = "Błąd, wyrażenie powinno składać się tylko z liter")]
    public string miasto { get; set; }
    [Required(ErrorMessage = "Proszę wprowadzić państwo")]
    [RegularExpression(@"^[0-9A-ZĄĘŁŃÓŚŹŻ]+[0-9a-zA-ZąćęłńóśźżĄĘŁŃÓŚŹŻ''-'\s]*$", ErrorMessage = "Błąd, wyrażenie powinno składać się tylko z liter")]
    public string panstwo { get; set; }
    public Nullable<int> id_uzytkownik { get; set; }
    public string szerokosc { get; set; }
    public string dlugosc { get; set; }
    public string nr_mieszkania { get; set; }




    public virtual Uzytkownik Uzytkownik { get; set; }
}
