//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities3 : DbContext
    {
        public Entities3()
            : base("name=Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Dyscyplina> Dyscyplina { get; set; }
        public virtual DbSet<Kwalifikacja> Kwalifikacja { get; set; }
        public virtual DbSet<Lista_dyscyplin> Lista_dyscyplin { get; set; }
        public virtual DbSet<Lista_kwalifikacji> Lista_kwalifikacji { get; set; }
        public virtual DbSet<Lista_spotkan> Lista_spotkan { get; set; }
        public virtual DbSet<Lista_Uslug> Lista_Uslug { get; set; }
        public virtual DbSet<Opinia> Opinia { get; set; }
        public virtual DbSet<Opinia_Szczegoly> Opinia_Szczegoly { get; set; }
        public virtual DbSet<Spolecznosc> Spolecznosc { get; set; }
        public virtual DbSet<Spotkanie> Spotkanie { get; set; }
        public virtual DbSet<Usluga> Usluga { get; set; }
        public virtual DbSet<Uzytkownik> Uzytkownik { get; set; }
    }
}
