//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FitBooking.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

public partial class Kwalifikacja
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Kwalifikacja()
    {
        this.Lista_kwalifikacji = new HashSet<Lista_kwalifikacji>();
    }

    public int Id { get; set; }
    [Required(ErrorMessage = "Proszę wprowadzić nazwę kwalifikacji")]
    [RegularExpression(@"^[A-Za-ząćęłńóśźżĄĘŁŃÓŚŹŻ]+[a-zA-ZąćęłńóśźżĄĘŁŃÓŚŹŻ.''-'\s]*$", ErrorMessage = "Błąd, wyrażenie powinno składać się tylko z liter")]
    public string nazwa { get; set; }
    [Required(ErrorMessage = "Proszę wprowadzić opis")]
    [RegularExpression(@"^[0-9A-Za-ząćęłńóśźżĄĘŁŃÓŚŹŻ]+[0-9a-zA-ZąćęłńóśźżĄĘŁŃÓŚŹŻ.''-'\s]*$", ErrorMessage = "Błąd, wyrażenie powinno składać się tylko z liter i cyfr")]
    public string opis { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Lista_kwalifikacji> Lista_kwalifikacji { get; set; }
}
