//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Collections.Generic;
    
    public partial class Lista_spotkan
    {
        public int Id { get; set; }
        public Nullable<int> id_funkcyjna { get; set; }
        public Nullable<int> id_klient { get; set; }
        public Nullable<int> id_spotkanie { get; set; }
        public string status { get; set; }
    
        public virtual Spotkanie Spotkanie { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
    }

