//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FitBooking.Models;
using System;
using System.Collections.Generic;

public partial class Lista_dyscyplin
{
    public int Id { get; set; }
    public int id_uzytkownik { get; set; }
    public int id_dyscyplina { get; set; }
    public List<Dyscyplina> Dyscypliny { get; set; }

    public virtual Dyscyplina Dyscyplina { get; set; }
    public virtual Uzytkownik Uzytkownik { get; set; }
}
