//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Collections.Generic;
    
    public partial class Opinia_Szczegoly
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public int id_opinia { get; set; }
        public int id_uzytkownik { get; set; }
    
        public virtual Opinia Opinia { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }

