//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using FitBooking.Models;
using System;
    using System.Collections.Generic;
    
    public partial class Opinia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opinia()
        {
            this.Opinia_Szczegoly = new HashSet<Opinia_Szczegoly>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> ocena { get; set; }
        public string opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinia_Szczegoly> Opinia_Szczegoly { get; set; }
    }

