//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Collections.Generic;
    
    public partial class Spolecznosc
    {
        public int Id { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string snapchat { get; set; }
        public string twitter { get; set; }
        public Nullable<int> id_uzytkownik { get; set; }
    
        public virtual Uzytkownik Uzytkownik { get; set; }
    }

