//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using DHTMLX.Scheduler;
using FitBooking.Models;
using System;
using System.Collections.Generic;
    
    public partial class Spotkanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    [DHXJson(Ignore = true)]
    public Spotkanie()
        {
            this.Lista_spotkan = new HashSet<Lista_spotkan>();
        }

    [DHXJson(Alias = "id")]
    public int Id { get; set; }
    [DHXJson(Alias = "text")]
    public string opis { get; set; }
    [DHXJson(Alias = "start_date")]
    public Nullable<System.DateTime> data_start { get; set; }
    [DHXJson(Alias = "end_date")]
    public Nullable<System.DateTime> data_koniec { get; set; }
    public string color { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [DHXJson(Ignore = true)]
    public virtual ICollection<Lista_spotkan> Lista_spotkan { get; set; }
    }

